// Copyright 2022 noppikinatta
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package asset

import (
	"bytes"
	"embed"
	"errors"
	"fmt"
	"io"
	"log"
	"strconv"
	"strings"

	"github.com/hajimehoshi/ebiten/v2/audio"
	"github.com/hajimehoshi/ebiten/v2/audio/mp3"
	"github.com/hajimehoshi/ebiten/v2/audio/vorbis"
	"github.com/hajimehoshi/ebiten/v2/audio/wav"
)

// seFS embeds the sound EFFECTS as loose wav files. SE are small and
// self-authored placeholders (generated by `make sound-gen`), so there is no
// licensing reason to obfuscate them: they are committed and embedded directly,
// like the BGM. Each effect is sound/se/<name>.wav.
//
//go:embed sound/se/*.wav
var seFS embed.FS

// bgmFS embeds the whole BGM directory. BGM is self-authored (no license
// concern), so it is committed and embedded directly. Each track may be present
// as a .wav (the authoring master) and/or a .ogg produced by `make bgm-ogg`;
// loadBGM prefers the .ogg (far smaller for the web build) and falls back to the
// .wav. Because the whole directory is embedded, dropping the .wav once the .ogg
// is verified ships ogg-only with no code change.
//
//go:embed sound/bgm
var bgmFS embed.FS

const sampleRate int = 48000

var context *audio.Context

func init() {
	context = audio.NewContext(sampleRate)
	seBytes = map[Sound][]byte{}
}

// Sound identifies a one-shot sound effect; each Play spins up a fresh, cheap
// player so effects may overlap. Each weapon kind has its own fire SE.
type Sound int

const (
	SEFireCannon Sound = iota
	SEFireShotgun
	SEFireSniper
	SEFireLaser
	SEFireGatling
	SEFireGrenade
	SEFireCIWS
	SEFireMissile
	SEExplosion
	SEPlayerHit
)

// BGMTrack identifies a looping background track. PlayBGM switches between them.
type BGMTrack int

const (
	BGMTitle BGMTrack = iota // opening + title screens
	BGMGame                  // in-game + result screens
)

type fileType int

const (
	fileTypeWav fileType = iota
	fileTypeMp3
	fileTypeOgg
)

// soundSpec describes how to load one sound effect. name is the file base name
// under sound/se (e.g. "fire_cannon" → sound/se/fire_cannon.wav); fileType
// selects the decoder.
type soundSpec struct {
	name     string
	sound    Sound
	fileType fileType
	volume   float64
}

// seSpecs are the one-shot effects, each embedded as sound/se/<name>.wav. Each
// weapon kind has its own fire entry. BGM is handled separately.
var seSpecs = []soundSpec{
	{"fire_cannon", SEFireCannon, fileTypeWav, 0.2},
	{"fire_shotgun", SEFireShotgun, fileTypeWav, 0.2},
	{"fire_sniper", SEFireSniper, fileTypeWav, 0.2},
	{"fire_laser", SEFireLaser, fileTypeWav, 0.2},
	{"fire_gatling", SEFireGatling, fileTypeWav, 0.15},
	{"fire_grenade", SEFireGrenade, fileTypeWav, 0.25},
	{"fire_ciws", SEFireCIWS, fileTypeWav, 0.15},
	{"fire_missile", SEFireMissile, fileTypeWav, 0.25},
	{"explosion", SEExplosion, fileTypeWav, 0.3},
	{"hit", SEPlayerHit, fileTypeWav, 0.4},
}

// bgmSpec describes a BGM track: its file base name (looked up in bgmFS as
// <name>.ogg / <name>.wav) and playback volume.
type bgmSpec struct {
	track  BGMTrack
	name   string
	volume float64
}

var bgmSpecs = []bgmSpec{
	{BGMTitle, "bgm_title", 0.50},
	{BGMGame, "bgm_game", 0.35},
}

// seBytes holds the decoded PCM for each one-shot effect so PlaySound can create
// a fresh player per play (allowing the same SE to overlap). bgmPlayers holds one
// reusable looping player per track; currentBGM tracks which is playing so
// re-requesting the active track is a no-op (seamless across scenes that share a
// track).
var (
	seBytes    map[Sound][]byte
	seVolume   = map[Sound]float64{}
	bgmPlayers = map[BGMTrack]*audio.Player{}
	currentBGM = BGMTrack(-1)
	bgmPlaying bool
)

// LoadSounds decodes the BGM and the sound effects, both embedded directly. A
// failed asset (missing file or undecodable bytes) is logged and skipped so a
// single bad asset does not take down the whole game; assets can be swapped by
// replacing the files in asset/sound/se (SE) or asset/sound/bgm (BGM).
func LoadSounds() error {
	for _, b := range bgmSpecs {
		if err := loadBGM(b); err != nil {
			log.Printf("skip loading BGM %d: %v", b.track, err)
		}
	}

	for _, s := range seSpecs {
		resource, err := seFS.ReadFile("sound/se/" + s.name + ".wav")
		if err != nil {
			log.Printf("skip loading SE %q: %v", s.name, err)
			continue
		}
		if err := loadSE(s, resource); err != nil {
			log.Printf("skip loading SE %q: %v", s.name, err)
			continue
		}
	}
	return nil
}

func decode(resource []byte, ftype fileType) (io.ReadSeeker, error) {
	switch ftype {
	case fileTypeWav:
		return wav.DecodeWithSampleRate(sampleRate, bytes.NewReader(resource))
	case fileTypeMp3:
		return mp3.DecodeWithSampleRate(sampleRate, bytes.NewReader(resource))
	case fileTypeOgg:
		return vorbis.DecodeWithSampleRate(sampleRate, bytes.NewReader(resource))
	default:
		return nil, errors.New("not supported filetype")
	}
}

// loadBGM decodes one background track into its reusable looping player. It
// prefers the Ogg Vorbis form (<name>.ogg, far smaller for the web build), using
// the exact loop length recorded by `make bgm-ogg` in <name>.ogg.loop so the
// lossy stream still loops seamlessly; if no usable .ogg is present it falls back
// to the .wav master, whose decoded Length() is exact.
func loadBGM(b bgmSpec) error {
	stream, loopLen, err := decodeBGM(b.name)
	if err != nil {
		return err
	}
	p, err := context.NewPlayer(audio.NewInfiniteLoop(stream, loopLen))
	if err != nil {
		return err
	}
	p.SetVolume(b.volume)
	bgmPlayers[b.track] = p
	return nil
}

// decodeBGM returns a looping stream and its loop length in bytes for track
// `name`, preferring <name>.ogg + <name>.ogg.loop over <name>.wav.
func decodeBGM(name string) (io.ReadSeeker, int64, error) {
	if ogg, err := bgmFS.ReadFile("sound/bgm/" + name + ".ogg"); err == nil {
		loopLen, lerr := readLoopLen(name)
		if lerr != nil {
			log.Printf("BGM %q: .ogg present but loop length unusable (%v); falling back to wav", name, lerr)
		} else if stream, derr := decode(ogg, fileTypeOgg); derr != nil {
			log.Printf("BGM %q: .ogg failed to decode (%v); falling back to wav", name, derr)
		} else {
			return stream, loopLen, nil
		}
	}
	wavBytes, err := bgmFS.ReadFile("sound/bgm/" + name + ".wav")
	if err != nil {
		return nil, 0, fmt.Errorf("no .ogg or .wav for BGM %q", name)
	}
	stream, err := decode(wavBytes, fileTypeWav)
	if err != nil {
		return nil, 0, err
	}
	// The wav decoder's Length() is exact, so the whole stream loops cleanly.
	var loopLen int64
	if l, ok := stream.(interface{ Length() int64 }); ok {
		loopLen = l.Length()
	}
	return stream, loopLen, nil
}

// readLoopLen parses the loop length (bytes, decimal) recorded next to the .ogg
// by the wav2ogg tool.
func readLoopLen(name string) (int64, error) {
	b, err := bgmFS.ReadFile("sound/bgm/" + name + ".ogg.loop")
	if err != nil {
		return 0, err
	}
	n, err := strconv.ParseInt(strings.TrimSpace(string(b)), 10, 64)
	if err != nil {
		return 0, err
	}
	if n <= 0 {
		return 0, fmt.Errorf("non-positive loop length %d", n)
	}
	return n, nil
}

// loadSE decodes a one-shot effect, keeping the PCM so each play gets its own
// player (allowing the same SE to overlap).
func loadSE(s soundSpec, resource []byte) error {
	stream, err := decode(resource, s.fileType)
	if err != nil {
		return err
	}
	pcm, err := io.ReadAll(stream)
	if err != nil {
		return err
	}
	seBytes[s.sound] = pcm
	seVolume[s.sound] = s.volume
	return nil
}

// PlaySound plays a one-shot effect: a fresh, overlapping player. Unloaded
// sounds are a no-op.
func PlaySound(s Sound) {
	pcm := seBytes[s]
	if pcm == nil {
		return
	}
	p := context.NewPlayerFromBytes(pcm)
	p.SetVolume(seVolume[s])
	p.Play() // GC'd once playback finishes
}

// PlayBGM plays the given looping track. Re-requesting the track that is already
// playing is a no-op, so scenes that share a track (opening↔title,
// in-game↔result) keep the music seamless; switching tracks stops the previous
// one and starts the new from the top.
func PlayBGM(track BGMTrack) {
	if bgmPlaying && currentBGM == track {
		return
	}
	if cur := bgmPlayers[currentBGM]; cur != nil {
		cur.Pause()
	}
	currentBGM = track
	p := bgmPlayers[track]
	if p == nil {
		bgmPlaying = false
		return
	}
	if err := p.Rewind(); err != nil {
		log.Println(err)
	}
	p.Play()
	bgmPlaying = true
}

// StopBGM pauses the current background track.
func StopBGM() {
	if cur := bgmPlayers[currentBGM]; cur != nil {
		cur.Pause()
	}
	bgmPlaying = false
}
